import {
  ConflictException,
  InternalServerErrorException,
} from '@nestjs/common';
import { EntityRepository, Repository } from 'typeorm';
import { AuthCredentialsDto } from './dto/auth-credentials.dto';
import { User } from './user.entity';

@EntityRepository(User)
export class UsersRepository extends Repository<User> {
  /**
   * Takes the user details, creates a new user and if the username is not already taken, saves the user
   *
   * @param {AuthCredentialsDto} authCredentialDto
   * @return {*}  {Promise<void>}
   * @memberof UsersRepository
   */
  async createUser(authCredentialDto: AuthCredentialsDto): Promise<void> {
    const { username, password } = authCredentialDto;

    const user = this.create({
      // Do not specify id because in the Entity the id is automatically generated by typeorm with uuid
      username,
      password,
    });

    try {
      await this.save(user);
    } catch (err) {
      if (err.code === '23505') {
        // duplicate username 23505 postgres error
        throw new ConflictException('Username already exists');
      } else {
        // If there is an error with code different from 23505, return internal server error
        throw new InternalServerErrorException();
      }
    }
  }
}
